language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.2

before_install:
  - brew update
  - brew tap decentfoundation/DCore

cache:
  timeout: 600
  directories:
    /usr/local/Cellar
    /usr/local/opt

script:
  - brew install --build-bottle --verbose --HEAD DCore
  - brew bottle --root-url=https://dl.bintray.com/decentfoundation/homebrew DCore
  - scripts/MacOS/prepare_dist.sh /usr/local/opt/DCore $TRAVIS_BUILD_NUMBER.$(date -u "+%H%M")
  - pkgbuild --root scripts/MacOS/dist --component-plist scripts/MacOS/decent_pkg.plist dcore.$(ls dcore-* | sed 's/dcore-.*\.\(.*\)\.bottle\.tar\.gz/\1/').pkg

deploy:
  skip_cleanup: true
  provider: bintray
  file: .bintray.json
  user: decent-dcore
  key:
    secure: W1hzW/MMczcvNxTeuMd021y1Gxg4yCuq7mqryyS7dbSbWfdbfQmLQJHvg1wqY7sES37XHTDSY3J/Y7IuKnY4pWX40ERQpkGZYqJFf1dx43iw6ETSL8Fb81rZVi+ykxZ4UcjZ6LGhzRMnY2HRlC9i32o/J742StHi6HHpVf3fsxz5f0pCElp18KrC72S05FIJ4dKT0whY4zTLG6T+laYDyB1F2EGjLC1mCMp7kJQoT6WlVjWy+N3+CxIjWKFP7xfO1nf7MveXYBwOh7rATWc/h44Lu9q8wHXl3CeUOXbuwf2N7AW19Zr5ifcyPx1/ooqjb6eR/FH6ENUxPhkRaGHLukLzsp+w97VgEpgeY64J2XqJdBoD2GUA4qH2TjNUiZGxZfxfrEMqv/xkeR4pTTGd0brWUfxwjoYyZewYYWwmZqwR0Cl3/WGm2DCI0WGM39LFGT1Dmk8JbfFBdTZNcJnoDXAxx9GoY6GURaE7CS0p7+xaAGewioZlvc76VO/5sCg/5GnyQbKqknQBekrbKBiMjDGKY5T94atGa8XQub4fS1HhzVvjKp9Sxj/BM7IVEKLghc0SWVK9iE0mgpspf9/wYWIyfaCBw06x3T9la3D1p/nI9EU9oOh6SPomyGAT43+syVqiVNo2XiUmW7W93KeZeM9FOwLtRDVuI2+BfnZILOQ=
  on:
    branch: develop
