language: cpp

sudo: required

os:
  - linux
  - osx

dist: xerus

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc



# Handle git submodules yourself.
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - cat .gitmodules
  - sed -i 's/git@github.com:/https:\/\/traceon:a6769af912a7248e199e82c06d470208810562ae@github.com\//' .gitmodules
  - git submodule update --init --recursive



install:
  - if [ $TRAVIS_OS_NAME == linux ] ; then sudo apt-get update -qq && sudo apt-get install -qq build-essential autotools-dev automake autoconf libtool make cmake gcc g++ clang flex bison doxygen gettext git google-perftools libgoogle-perftools-dev libreadline-dev libcrypto++-dev libgmp-dev libdb-dev libdb++-dev libssl-dev libncurses5-dev libboost-all-dev ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew tap homebrew/versions && brew update && brew doctor && brew install automake autoconf libtool cmake berkeley-db boost160 cryptopp libtorrent-rasterbar doxygen byacc flex gettext git pbc gmp ipfs openssl readline gperftools ; fi

script:
  - mkdir -p build && cd build && cmake -D CMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" .. && cmake --build . --target all -- -j -l 3.0 && cmake --build . --target install

notifications:
  email:
    on_success: change
    on_failure: always
