language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.2

before_install:
  - brew update
  - brew tap decentfoundation/DCore

script:
  - brew install --build-bottle --verbose --HEAD DCore
  - brew bottle --root-url=https://dl.bintray.com/decentfoundation/homebrew DCore
  - cd scripts/MacOS
  - ./prepare_dist.sh /usr/local/opt/DCore $TRAVIS_BUILD_NUMBER.$(date -u "+%H%M")
  - pkgbuild --root dist --component-plist decent_pkg.plist DCore.dev.pkg

deploy:
  skip_cleanup: true
  provider: bintray
  file: .bintray.json
  user: decent-dcore
  key:
    secure: uh3ADpcP6Ng2Jj0T2fd08y6I12SWZY2WZTquFVzOa6T4ki7C5d7JAd3Y1zkyAFHy3/X4GUoj2hUGql+XQOz3HV9DF8ou9fQu9lMtVhqQDyejNttHP77BLQeOazIM4HqgP7JXvG4o9HOOjzrwfadekMWJjFJUvVnLaUlqUvDJNR8NZrppmsp+8pZzWF4uFN9pnIJ68W5W/7/mFAzIWkJJPMC4datVpMLU+JdeWGSC5MY0cMzy9H7ol7jePqBG1IIUil8CTPY96hh9K/sXkb0dgA3SbyDY/QhlqFhNk00k8rGaefeaX08jzsXjn1oqLfMsmPWf1S3p1mqybzDr1GMl+2vm+B88MbwlhnWgcGhcPG4jclrKlj1vaYliY2nFJq6C/nN2UAtstC4NzLDgnSvDndxumP3PHqK3C8kzlxf9SZxUNG8E0pWUCLKTD3/dzxMtcedyjtI/0CQmeRksDGWWLn3ByG/CLovzHn9IrHDte6TjYDHelpdpZwR7zEoUJ2IEzwQqAeqzVdPC2op8VEG9u4UA+k4tFLSALQFicGyH/wmDeHZL8Ef1jCDJHIsN4OTowNWulxUGqlnvHI/rrWfnkFfVrvY3gbedl9Q31VWZ8kM2ZdUuDYX5K1K/ThgHYVq1ik3TCtDYB9BnEi3z5oWZllIistbMArUmSGhseN/9KAY=
  on:
    branch: develop
