language: cpp

sudo: required

os:
  - linux
  - osx

osx_image: xcode8.2

dist: xerus

compiler:
  - gcc
  - clang

env:
  - DECENT_CMAKE_GENERATOR="Unix Makefiles" DECENT_CMAKE_BUILD_TYPE="Release"
  - DECENT_CMAKE_GENERATOR="Unix Makefiles" DECENT_CMAKE_BUILD_TYPE="Debug"
  - DECENT_CMAKE_GENERATOR="Xcode" DECENT_CMAKE_BUILD_TYPE="Release"
  - DECENT_CMAKE_GENERATOR="Xcode" DECENT_CMAKE_BUILD_TYPE="Debug"

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      env: DECENT_CMAKE_GENERATOR="Xcode" DECENT_CMAKE_BUILD_TYPE="Release"
    - os: linux
      env: DECENT_CMAKE_GENERATOR="Xcode" DECENT_CMAKE_BUILD_TYPE="Debug"



# Handle git submodules manually.
git:
  submodules: false

# Replace HTTPS URLs of private repos in .gitmodules to SSH to workaround auth errors, then initialize submodules manually.
before_install:
  - perl -pi -e 's/https\:\/\/github\.com\/DECENTfoundation\/DECENT-Network\.wiki\.git/git\@github\.com\:DECENTfoundation\/DECENT-Network\.wiki\.git/' .gitmodules
  - perl -pi -e 's/https\:\/\/github\.com\/DECENTfoundation\/pbc\.git/git\@github\.com\:DECENTfoundation\/pbc\.git/' .gitmodules
  - git submodule update --init --recursive



install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get update -qq && sudo apt-get install -qq build-essential autotools-dev automake autoconf libtool make cmake gcc g++ clang flex bison doxygen gettext git google-perftools libgoogle-perftools-dev libreadline-dev libcrypto++-dev libgmp-dev libdb-dev libdb++-dev libssl-dev libncurses5-dev libboost-all-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" - --force && rm -rf /usr/local/* && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew update && brew upgrade && brew cleanup && brew doctor && brew tap homebrew/versions && brew update && brew install automake autoconf libtool cmake berkeley-db boost160 cryptopp libtorrent-rasterbar doxygen byacc flex gettext git pbc gmp ipfs openssl readline gperftools && brew doctor ; fi

script:
  - DECENT_CMAKE_TARGET_ALL="all"
  - DECENT_CMAKE_TARGET_INSTALL="install"
  - DECENT_CMAKE_EXTRA_BUILD_PARAMS="-j 10 -l 3.0 VERBOSE=1"
  - if [ "$DECENT_CMAKE_GENERATOR" == "Xcode" ] ; then unset CC && unset CXX && DECENT_CMAKE_TARGET_ALL="ALL_BUILD" && DECENT_CMAKE_EXTRA_BUILD_PARAMS="-jobs 10 -verbose" ; fi
  - mkdir -p build && cd build && cmake -D CMAKE_BUILD_TYPE="$DECENT_CMAKE_BUILD_TYPE" -G "$DECENT_CMAKE_GENERATOR" .. && cmake --build . --target "$DECENT_CMAKE_TARGET_ALL" -- $DECENT_CMAKE_EXTRA_BUILD_PARAMS && cmake --build . --target "$DECENT_CMAKE_TARGET_INSTALL"

notifications:
  email:
    on_success: change
    on_failure: always
